CREATE TABLE IF NOT EXISTS product(
id_cliente bigint generated by default as identity,
name varchar(50) not null,
description varchar(50) null,
price decimal(19,2) not null default 0,
primary key (id_cliente)
);

